# Generated by Django 3.0.5 on 2020-04-19 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
        migrations.AddField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reserved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reserved_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reservee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Customers'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reserver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Restaurants'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
