# Generated by Django 3.0.5 on 2020-04-20 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200420_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
